var loadCLD2=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function g(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:aa(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var l="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var p=ba(this);function r(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];if(!(f in c))break a;c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&l(c,a,{configurable:!0,writable:!0,value:b})}}
function t(){this.G=!1;this.B=null;this.C=void 0;this.v=1;this.J=this.F=0;this.D=null}function u(a){if(a.G)throw new TypeError("Generator is already running");a.G=!0}t.prototype.H=function(a){this.C=a};function v(a,b){a.D={R:b,$:!0};a.v=a.F||a.J}t.prototype.return=function(a){this.D={return:a};this.v=this.J};function x(a,b,c){a.v=c;return{value:b}}function y(a){a.F=0;var b=a.D.R;a.D=null;return b}function ca(a){this.v=new t;this.B=a}
function da(a,b){u(a.v);var c=a.v.B;if(c)return z(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.v.return);a.v.return(b);return C(a)}function z(a,b,c,d){try{var f=b.call(a.v.B,c);if(!(f instanceof Object))throw new TypeError("Iterator result "+f+" is not an object");if(!f.done)return a.v.G=!1,f;var h=f.value}catch(e){return a.v.B=null,v(a.v,e),C(a)}a.v.B=null;d.call(a.v,h);return C(a)}
function C(a){for(;a.v.v;)try{var b=a.B(a.v);if(b)return a.v.G=!1,{value:b.value,done:!1}}catch(c){a.v.C=void 0,v(a.v,c)}a.v.G=!1;if(a.v.D){b=a.v.D;a.v.D=null;if(b.$)throw b.R;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function ea(a){this.next=function(b){u(a.v);a.v.B?b=z(a,a.v.B.next,b,a.v.H):(a.v.H(b),b=C(a));return b};this.throw=function(b){u(a.v);a.v.B?b=z(a,a.v.B["throw"],b,a.v.H):(v(a.v,b),b=C(a));return b};this.return=function(b){return da(a,b)};this[Symbol.iterator]=function(){return this}}function fa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,f){function h(e){e.done?d(e.value):Promise.resolve(e.value).then(b,c).then(h,f)}h(a.next())})}
function D(a){return fa(new ea(new ca(a)))}r("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(h||"")+"_"+f++,h)}function c(h,e){this.v=h;l(this,"description",{configurable:!0,writable:!0,value:e})}if(a)return a;c.prototype.toString=function(){return this.v};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",f=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=p[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&l(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ha(aa(this))}})}return a});function ha(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
r("Promise",function(a){function b(e){this.B=0;this.C=void 0;this.v=[];this.H=!1;var k=this.D();try{e(k.resolve,k.reject)}catch(m){k.reject(m)}}function c(){this.v=null}function d(e){return e instanceof b?e:new b(function(k){k(e)})}if(a)return a;c.prototype.B=function(e){if(null==this.v){this.v=[];var k=this;this.C(function(){k.F()})}this.v.push(e)};var f=p.setTimeout;c.prototype.C=function(e){f(e,0)};c.prototype.F=function(){for(;this.v&&this.v.length;){var e=this.v;this.v=[];for(var k=0;k<e.length;++k){var m=
e[k];e[k]=null;try{m()}catch(n){this.D(n)}}}this.v=null};c.prototype.D=function(e){this.C(function(){throw e;})};b.prototype.D=function(){function e(n){return function(q){m||(m=!0,n.call(k,q))}}var k=this,m=!1;return{resolve:e(this.V),reject:e(this.F)}};b.prototype.V=function(e){if(e===this)this.F(new TypeError("A Promise cannot resolve to itself"));else if(e instanceof b)this.X(e);else{a:switch(typeof e){case "object":var k=null!=e;break a;case "function":k=!0;break a;default:k=!1}k?this.U(e):this.G(e)}};
b.prototype.U=function(e){var k=void 0;try{k=e.then}catch(m){this.F(m);return}"function"==typeof k?this.Y(k,e):this.G(e)};b.prototype.F=function(e){this.J(2,e)};b.prototype.G=function(e){this.J(1,e)};b.prototype.J=function(e,k){if(0!=this.B)throw Error("Cannot settle("+e+", "+k+"): Promise already settled in state"+this.B);this.B=e;this.C=k;2===this.B&&this.W();this.S()};b.prototype.W=function(){var e=this;f(function(){if(e.T()){var k=p.console;"undefined"!==typeof k&&k.error(e.C)}},1)};b.prototype.T=
function(){if(this.H)return!1;var e=p.CustomEvent,k=p.Event,m=p.dispatchEvent;if("undefined"===typeof m)return!0;"function"===typeof e?e=new e("unhandledrejection",{cancelable:!0}):"function"===typeof k?e=new k("unhandledrejection",{cancelable:!0}):(e=p.document.createEvent("CustomEvent"),e.initCustomEvent("unhandledrejection",!1,!0,e));e.promise=this;e.reason=this.C;return m(e)};b.prototype.S=function(){if(null!=this.v){for(var e=0;e<this.v.length;++e)h.B(this.v[e]);this.v=null}};var h=new c;b.prototype.X=
function(e){var k=this.D();e.N(k.resolve,k.reject)};b.prototype.Y=function(e,k){var m=this.D();try{e.call(k,m.resolve,m.reject)}catch(n){m.reject(n)}};b.prototype.then=function(e,k){function m(w,A){return"function"==typeof w?function(Y){try{n(w(Y))}catch(Z){q(Z)}}:A}var n,q,B=new b(function(w,A){n=w;q=A});this.N(m(e,n),m(k,q));return B};b.prototype.catch=function(e){return this.then(void 0,e)};b.prototype.N=function(e,k){function m(){switch(n.B){case 1:e(n.C);break;case 2:k(n.C);break;default:throw Error("Unexpected state: "+
n.B);}}var n=this;null==this.v?h.B(m):this.v.push(m);this.H=!0};b.resolve=d;b.reject=function(e){return new b(function(k,m){m(e)})};b.race=function(e){return new b(function(k,m){for(var n=g(e),q=n.next();!q.done;q=n.next())d(q.value).N(k,m)})};b.all=function(e){var k=g(e),m=k.next();return m.done?d([]):new b(function(n,q){function B(Y){return function(Z){w[Y]=Z;A--;0==A&&n(w)}}var w=[],A=0;do w.push(void 0),A++,d(m.value).N(B(w.length-1),q),m=k.next();while(!m.done)})};return b});
r("globalThis",function(a){return a||p});function ia(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
r("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=ia(this,b,"startsWith"),f=d.length,h=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var e=0;e<h&&c<f;)if(d[c++]!=b[e++])return!1;return e>=h}});r("String.prototype.codePointAt",function(a){return a?a:function(b){var c=ia(this,null,"codePointAt"),d=c.length;b=Number(b)||0;if(0<=b&&b<d){b|=0;var f=c.charCodeAt(b);if(55296>f||56319<f||b+1===d)return f;b=c.charCodeAt(b+1);return 56320>b||57343<b?f:1024*(f-55296)+b+9216}}});
function ja(a,b){a instanceof String&&(a+="");var c=0,d=!1,f={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};f[Symbol.iterator]=function(){return f};return f}r("Array.prototype.keys",function(a){return a?a:function(){return ja(this,function(b){return b})}});
var E=moduleArg,ka=!!globalThis.window,la=!!globalThis.WorkerGlobalScope,ma,na,oa,pa=(null==(ma=globalThis.process)?void 0:null==(na=ma.versions)?void 0:na.node)&&"renderer"!=(null==(oa=globalThis.process)?void 0:oa.type);"undefined"!=typeof __filename?_scriptName=__filename:la&&(_scriptName=self.location.href);var F="",qa,G;
if(pa){var fs=require("fs");F=__dirname+"/";G=function(a){a=H(a)?new URL(a):a;return fs.readFileSync(a)};qa=function(a){var b=void 0===b?!0:b;var c;return D(function(d){a=H(a)?new URL(a):a;c=fs.readFileSync(a,b?void 0:"utf8");return d.return(c)})};process.argv.slice(2)}else if(ka||la){try{F=(new URL(".",_scriptName)).href}catch(a){}la&&(G=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});qa=function(a){var b;return D(function(c){if(1==
c.v)return H(a)?c.return(new Promise(function(d,f){var h=new XMLHttpRequest;h.open("GET",a,!0);h.responseType="arraybuffer";h.onload=function(){200==h.status||0==h.status&&h.response?d(h.response):f(h.status)};h.onerror=f;h.send(null)})):x(c,fetch(a,{credentials:"same-origin"}),2);b=c.C;if(b.ok)return c.return(b.arrayBuffer());throw Error(b.status+" : "+b.url);})}}var ra=console.log.bind(console),I=console.error.bind(console),J,sa=!1;function H(a){return a.startsWith("file://")}
var ta,ua,va,K,L,wa=!1;function xa(){var a=M.buffer;va=new Int8Array(a);new Int16Array(a);K=new Uint8Array(a);new Uint16Array(a);new Int32Array(a);L=new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function N(a){var b;null==(b=E.onAbort)||b.call(E,a);a="Aborted("+a+")";I(a);sa=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");var c;null==(c=ua)||c(a);throw a;}var O;
function ya(a){var b;return D(function(c){switch(c.v){case 1:if(J){c.v=2;break}c.F=3;return x(c,qa(a),5);case 5:return b=c.C,c.return(new Uint8Array(b));case 3:y(c);case 2:var d=c.return;if(a==O&&J)var f=new Uint8Array(J);else if(G)f=G(a);else throw"both async and sync fetching of the wasm failed";return d.call(c,f)}})}
function za(a,b){var c,d,f;return D(function(h){switch(h.v){case 1:return h.F=2,x(h,ya(a),4);case 4:return c=h.C,x(h,WebAssembly.instantiate(c,b),5);case 5:return d=h.C,h.return(d);case 2:f=y(h),I("failed to asynchronously prepare wasm: "+f),N(f),h.v=0}})}
function Aa(a){var b=J,c=O,d,f,h;return D(function(e){switch(e.v){case 1:if(b||H(c)||pa){e.v=2;break}e.F=3;d=fetch(c,{credentials:"same-origin"});return x(e,WebAssembly.instantiateStreaming(d,a),5);case 5:return f=e.C,e.return(f);case 3:h=y(e),I("wasm streaming compile failed: "+h),I("falling back to ArrayBuffer instantiation");case 2:return e.return(za(c,a))}})}function Ba(a){for(;0<a.length;)a.shift()(E)}var Ca=[],Da=[];function Ea(){var a=E.preRun.shift();Da.push(a)}
function Fa(a){this.A=a-24}var Ga=0,Ha=0,Ia=[null,[],[]],Ja=globalThis.TextDecoder&&new TextDecoder;
function Ka(a,b){b=void 0===b?0:b;var c=b;for(var d=c+void 0;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ja)return Ja.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var h=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|h);else{var e=a[b++]&63;f=224==(f&240)?(f&15)<<12|h<<6|e:(f&7)<<18|h<<12|e<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function La(a){return a?Ka(K,a):""}
var Ma=[];E.print&&(ra=E.print);E.printErr&&(I=E.printErr);E.wasmBinary&&(J=E.wasmBinary);if(E.preInit)for("function"==typeof E.preInit&&(E.preInit=[E.preInit]);0<E.preInit.length;)E.preInit.shift()();
var Na,Oa,Pa,Qa,Ra,Sa,Ta,Ua,Va,Wa,Xa,Ya,M,Za={a:function(a,b,c){var d=new Fa(a);L[d.A+16>>2]=0;L[d.A+4>>2]=b;L[d.A+8>>2]=c;Ga=a;Ha++;throw Ga;},c:function(){return N("")},e:function(a,b){throw"Array index "+a+" out of bounds: [0,"+b+")";},d:function(a){var b=K.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-M.buffer.byteLength+65535)/65536|0;try{M.grow(d);xa();var f=1;break a}catch(h){}f=
void 0}if(f)return!0}return!1},b:function(a,b,c,d){for(var f=0,h=0;h<c;h++){var e=L[b>>2],k=L[b+4>>2];b+=8;for(var m=0;m<k;m++){var n=a,q=K[e+m],B=Ia[n];0===q||10===q?((1===n?ra:I)(Ka(B)),B.length=0):B.push(q)}f+=k}L[d>>2]=f;return 0}},P;
P=await (function(){function a(f){f=P=f.exports;E._webidl_free=f.h;E._webidl_malloc=f.i;Na=E._emscripten_bind_Language_getLanguageCode_0=f.j;Oa=E._emscripten_bind_Language___destroy___0=f.k;Pa=E._emscripten_bind_VoidPtr___destroy___0=f.l;Qa=E._emscripten_bind_LanguageGuess_getPercent_0=f.m;Ra=E._emscripten_bind_LanguageGuess_getLanguageCode_0=f.n;Sa=E._emscripten_bind_LanguageGuess___destroy___0=f.o;Ta=E._emscripten_bind_LanguageInfo_detectLanguage_2=f.p;Ua=E._emscripten_bind_LanguageInfo_detectLanguage_5=
f.q;Va=E._emscripten_bind_LanguageInfo_getIsReliable_0=f.r;Wa=E._emscripten_bind_LanguageInfo_getLanguageCode_0=f.s;Xa=E._emscripten_bind_LanguageInfo_get_languages_1=f.t;Ya=E._emscripten_bind_LanguageInfo___destroy___0=f.u;M=f.f;xa();return P}var b,c,d;return D(function(f){if(1==f.v){b={a:Za};if(E.instantiateWasm)return f.return(new Promise(function(h){E.instantiateWasm(b,function(e,k){h(a(e,k))})}));null!=O||(O=E.locateFile?E.locateFile("cld2.wasm",F):F+"cld2.wasm");return x(f,Aa(b),2)}c=f.C;d=
a(c.instance);return f.return(d)})}());
(function(){function a(){E.calledRun=!0;if(!sa){wa=!0;Ba(Ma);P.g();var b;null==(b=ta)||b(E);var c;null==(c=E.onRuntimeInitialized)||c.call(E);if(E.postRun)for("function"==typeof E.postRun&&(E.postRun=[E.postRun]);E.postRun.length;)b=E.postRun.shift(),Ca.push(b);Ba(Ca)}}if(E.preRun)for("function"==typeof E.preRun&&(E.preRun=[E.preRun]);E.preRun.length;)Ea();Ba(Da);E.setStatus?(E.setStatus("Running..."),setTimeout(function(){setTimeout(function(){return E.setStatus("")},1);a()},1)):a()})();
function Q(){}Q.prototype=Object.create(Q.prototype);Q.prototype.constructor=Q;Q.prototype.I=Q;Q.K={};E.WrapperObject=Q;function $a(a){return(a||Q).K}E.getCache=$a;function R(a,b){var c=$a(b),d=c[a];if(d)return d;d=Object.create((b||Q).prototype);d.A=a;return c[a]=d}E.wrapPointer=R;E.castObject=function(a,b){return R(a.A,b)};E.NULL=R(0);E.destroy=function(a){if(!a.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";a.__destroy__();delete $a(a.I)[a.A]};
E.compare=function(a,b){return a.A===b.A};E.getPointer=function(a){return a.A};E.getClass=function(a){return a.I};
var S={buffer:0,size:0,M:0,O:[],L:0,P:function(){if(S.L){for(var a=0;a<S.O.length;a++)E._webidl_free(S.O[a]);S.O.length=0;E._webidl_free(S.buffer);S.buffer=0;S.size+=S.L;S.L=0}S.buffer||(S.size+=128,S.buffer=E._webidl_malloc(S.size),S.buffer||N());S.M=0},alloc:function(a,b){S.buffer||N();a=a.length*b.BYTES_PER_ELEMENT;a=8*Math.ceil(a/8);S.M+a>=S.size?(0<a||N(),S.L+=a,b=E._webidl_malloc(a),S.O.push(b)):(b=S.buffer+S.M,S.M+=a);return b}};
function ab(a){if("string"===typeof a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b=Array(b+1);d=b.length;c=0;if(0<d){d=c+d-1;for(var f=0;f<a.length;++f){var h=a.codePointAt(f);if(127>=h){if(c>=d)break;b[c++]=h}else if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6;b[c++]=128|h&63}else if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12;b[c++]=128|h>>6&63;b[c++]=128|h&63}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63;b[c++]=128|
h>>6&63;b[c++]=128|h&63;f++}}b[c]=0}a=S.alloc(b,va);for(c=0;c<b.length;c++)va[a+c]=b[c];return a}return a}function T(){throw"cannot construct a Language, no constructor in IDL";}T.prototype=Object.create(Q.prototype);T.prototype.constructor=T;T.prototype.I=T;T.K={};E.Language=T;T.prototype.getLanguageCode=function(){return La(Na(this.A))};T.prototype.__destroy__=function(){Oa(this.A)};function U(){throw"cannot construct a VoidPtr, no constructor in IDL";}U.prototype=Object.create(Q.prototype);
U.prototype.constructor=U;U.prototype.I=U;U.K={};E.VoidPtr=U;U.prototype.__destroy__=function(){Pa(this.A)};function V(){throw"cannot construct a LanguageGuess, no constructor in IDL";}V.prototype=Object.create(T.prototype);V.prototype.constructor=V;V.prototype.I=V;V.K={};E.LanguageGuess=V;V.prototype.getPercent=function(){return Qa(this.A)};V.prototype.getLanguageCode=function(){return La(Ra(this.A))};V.prototype.__destroy__=function(){Sa(this.A)};
function W(){throw"cannot construct a LanguageInfo, no constructor in IDL";}W.prototype=Object.create(T.prototype);W.prototype.constructor=W;W.prototype.I=W;W.K={};E.LanguageInfo=W;
W.prototype.detectLanguage=function(a,b,c,d,f){S.P();a=a&&"object"===typeof a?a.A:ab(a);b&&"object"===typeof b&&(b=b.A);c=c&&"object"===typeof c?c.A:ab(c);d&&"object"===typeof d&&(d=d.A);f=f&&"object"===typeof f?f.A:ab(f);return void 0===c?R(Ta(a,b),W):void 0===d?R(_emscripten_bind_LanguageInfo_detectLanguage_3(a,b,c),W):void 0===f?R(_emscripten_bind_LanguageInfo_detectLanguage_4(a,b,c,d),W):R(Ua(a,b,c,d,f),W)};W.prototype.getIsReliable=function(){return!!Va(this.A)};W.prototype.getLanguageCode=function(){return La(Wa(this.A))};
W.prototype.get_languages=W.prototype.Z=function(a){var b=this.A;a&&"object"===typeof a&&(a=a.A);return R(Xa(b,a),V)};Object.defineProperty(W.prototype,"languages",{get:W.prototype.Z});W.prototype.__destroy__=function(){Ya(this.A)};S.alloc=S.alloc.bind(S);S.P=S.P.bind(S);
for(var X={ISO_8859_1:0,ISO_8859_2:1,ISO_8859_3:2,ISO_8859_4:3,ISO_8859_5:4,ISO_8859_6:5,ISO_8859_7:6,ISO_8859_8:7,ISO_8859_9:8,ISO_8859_10:9,JAPANESE_EUC_JP:10,EUC_JP:10,JAPANESE_SHIFT_JIS:11,SHIFT_JIS:11,JAPANESE_JIS:12,JIS:12,CHINESE_BIG5:13,BIG5:13,CHINESE_GB:14,CHINESE_EUC_CN:15,EUC_CN:15,KOREAN_EUC_KR:16,EUC_KR:16,UNICODE_UNUSED:17,CHINESE_EUC_DEC:18,EUC_DEC:18,CHINESE_CNS:19,CNS:19,CHINESE_BIG5_CP950:20,BIG5_CP950:20,JAPANESE_CP932:21,CP932:21,UTF8:22,UNKNOWN_ENCODING:23,ASCII_7BIT:24,RUSSIAN_KOI8_R:25,
KOI8_R:25,RUSSIAN_CP1251:26,CP1251:26,MSFT_CP1252:27,CP1252:27,RUSSIAN_KOI8_RU:28,KOI8_RU:28,MSFT_CP1250:29,CP1250:29,ISO_8859_15:30,MSFT_CP1254:31,CP1254:31,MSFT_CP1257:32,CP1257:32,ISO_8859_11:33,MSFT_CP874:34,CP874:34,MSFT_CP1256:35,CP1256:35,MSFT_CP1255:36,CP1255:36,ISO_8859_8_I:37,HEBREW_VISUAL:38,CZECH_CP852:39,CP852:39,CZECH_CSN_369103:40,CSN_369103:40,MSFT_CP1253:41,CP1253:41,RUSSIAN_CP866:42,CP866:42,ISO_8859_13:43,ISO_2022_KR:44,GBK:45,GB18030:46,BIG5_HKSCS:47,ISO_2022_CN:48,TSCII:49,TAMIL_MONO:50,
TAMIL_BI:51,JAGRAN:52,MACINTOSH_ROMAN:53,UTF7:54,BHASKAR:55,HTCHANAKYA:56,UTF16BE:57,UTF16LE:58,UTF32BE:59,UTF32LE:60,BINARYENC:61,HZ_GB_2312:62,UTF8UTF8:63,TAM_ELANGO:64,TAM_LTTMBARANI:65,TAM_SHREE:66,TAM_TBOOMIS:67,TAM_TMNEWS:68,TAM_WEBTAMIL:69,KDDI_SHIFT_JIS:70,DOCOMO_SHIFT_JIS:71,SOFTBANK_SHIFT_JIS:72,KDDI_ISO_2022_JP:73,ISO_2022_JP:73,SOFTBANK_ISO_2022_JP:74},bb=g(Object.keys(X)),cb=bb.next();!cb.done;cb=bb.next()){var db=cb.value;db.includes("_")&&(X[db.replace(/_/g,"")]=X[db])}
E.Encodings=X;wa?moduleRtn=E:moduleRtn=new Promise(function(a,b){ta=a;ua=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=loadCLD2;module.exports.default=loadCLD2}else if(typeof define==="function"&&define["amd"])define([],()=>loadCLD2);
