var loadCLD2=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;function ba(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function h(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if("number"==typeof a.length)return{next:ba(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}var l="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var n=ca(this);function r(a,b){if(b)a:{var c=n;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&l(c,a,{configurable:!0,writable:!0,value:b})}}
function t(){this.H=!1;this.C=null;this.D=void 0;this.A=1;this.K=this.G=0;this.F=null}function u(a){if(a.H)throw new TypeError("Generator is already running");a.H=!0}t.prototype.I=function(a){this.D=a};function v(a,b){a.F={S:b,aa:!0};a.A=a.G||a.K}t.prototype.return=function(a){this.F={return:a};this.A=this.K};function w(a,b,c){a.A=c;return{value:b}}function y(a){a.G=0;var b=a.F.S;a.F=null;return b}function da(a){this.A=new t;this.C=a}
function ea(a,b){u(a.A);var c=a.A.C;if(c)return z(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.A.return);a.A.return(b);return C(a)}function z(a,b,c,d){try{var e=b.call(a.A.C,c);if(!(e instanceof Object))throw new TypeError("Iterator result "+e+" is not an object");if(!e.done)return a.A.H=!1,e;var g=e.value}catch(f){return a.A.C=null,v(a.A,f),C(a)}a.A.C=null;d.call(a.A,g);return C(a)}
function C(a){for(;a.A.A;)try{var b=a.C(a.A);if(b)return a.A.H=!1,{value:b.value,done:!1}}catch(c){a.A.D=void 0,v(a.A,c)}a.A.H=!1;if(a.A.F){b=a.A.F;a.A.F=null;if(b.aa)throw b.S;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function fa(a){this.next=function(b){u(a.A);a.A.C?b=z(a,a.A.C.next,b,a.A.I):(a.A.I(b),b=C(a));return b};this.throw=function(b){u(a.A);a.A.C?b=z(a,a.A.C["throw"],b,a.A.I):(v(a.A,b),b=C(a));return b};this.return=function(b){return ea(a,b)};this[Symbol.iterator]=function(){return this}}function ha(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function g(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(g,e)}g(a.next())})}
function D(a){return ha(new fa(new da(a)))}r("Symbol",function(a){function b(g){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(g||"")+"_"+e++,g)}function c(g,f){this.A=g;l(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.A};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=n[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&l(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ia(ba(this))}})}return a});function ia(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
r("Promise",function(a){function b(f){this.C=0;this.D=void 0;this.A=[];this.I=!1;var k=this.F();try{f(k.resolve,k.reject)}catch(m){k.reject(m)}}function c(){this.A=null}function d(f){return f instanceof b?f:new b(function(k){k(f)})}if(a)return a;c.prototype.C=function(f){if(null==this.A){this.A=[];var k=this;this.D(function(){k.G()})}this.A.push(f)};var e=n.setTimeout;c.prototype.D=function(f){e(f,0)};c.prototype.G=function(){for(;this.A&&this.A.length;){var f=this.A;this.A=[];for(var k=0;k<f.length;++k){var m=
f[k];f[k]=null;try{m()}catch(p){this.F(p)}}}this.A=null};c.prototype.F=function(f){this.D(function(){throw f;})};b.prototype.F=function(){function f(p){return function(q){m||(m=!0,p.call(k,q))}}var k=this,m=!1;return{resolve:f(this.W),reject:f(this.G)}};b.prototype.W=function(f){if(f===this)this.G(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.Y(f);else{a:switch(typeof f){case "object":var k=null!=f;break a;case "function":k=!0;break a;default:k=!1}k?this.V(f):this.H(f)}};
b.prototype.V=function(f){var k=void 0;try{k=f.then}catch(m){this.G(m);return}"function"==typeof k?this.Z(k,f):this.H(f)};b.prototype.G=function(f){this.K(2,f)};b.prototype.H=function(f){this.K(1,f)};b.prototype.K=function(f,k){if(0!=this.C)throw Error("Cannot settle("+f+", "+k+"): Promise already settled in state"+this.C);this.C=f;this.D=k;2===this.C&&this.X();this.T()};b.prototype.X=function(){var f=this;e(function(){if(f.U()){var k=n.console;"undefined"!==typeof k&&k.error(f.D)}},1)};b.prototype.U=
function(){if(this.I)return!1;var f=n.CustomEvent,k=n.Event,m=n.dispatchEvent;if("undefined"===typeof m)return!0;"function"===typeof f?f=new f("unhandledrejection",{cancelable:!0}):"function"===typeof k?f=new k("unhandledrejection",{cancelable:!0}):(f=n.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.D;return m(f)};b.prototype.T=function(){if(null!=this.A){for(var f=0;f<this.A.length;++f)g.C(this.A[f]);this.A=null}};var g=new c;b.prototype.Y=
function(f){var k=this.F();f.O(k.resolve,k.reject)};b.prototype.Z=function(f,k){var m=this.F();try{f.call(k,m.resolve,m.reject)}catch(p){m.reject(p)}};b.prototype.then=function(f,k){function m(x,A){return"function"==typeof x?function(Z){try{p(x(Z))}catch(aa){q(aa)}}:A}var p,q,B=new b(function(x,A){p=x;q=A});this.O(m(f,p),m(k,q));return B};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.O=function(f,k){function m(){switch(p.C){case 1:f(p.D);break;case 2:k(p.D);break;default:throw Error("Unexpected state: "+
p.C);}}var p=this;null==this.A?g.C(m):this.A.push(m);this.I=!0};b.resolve=d;b.reject=function(f){return new b(function(k,m){m(f)})};b.race=function(f){return new b(function(k,m){for(var p=h(f),q=p.next();!q.done;q=p.next())d(q.value).O(k,m)})};b.all=function(f){var k=h(f),m=k.next();return m.done?d([]):new b(function(p,q){function B(Z){return function(aa){x[Z]=aa;A--;0==A&&p(x)}}var x=[],A=0;do x.push(void 0),A++,d(m.value).O(B(x.length-1),q),m=k.next();while(!m.done)})};return b});
r("globalThis",function(a){return a||n});function ja(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
r("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=ja(this,b,"startsWith"),e=d.length,g=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var f=0;f<g&&c<e;)if(d[c++]!=b[f++])return!1;return f>=g}});r("String.prototype.codePointAt",function(a){return a?a:function(b){var c=ja(this,null,"codePointAt"),d=c.length;b=Number(b)||0;if(0<=b&&b<d){b|=0;var e=c.charCodeAt(b);if(55296>e||56319<e||b+1===d)return e;b=c.charCodeAt(b+1);return 56320>b||57343<b?e:1024*(e-55296)+b+9216}}});
function ka(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var g=c++;return{value:b(g,a[g]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}r("Array.prototype.keys",function(a){return a?a:function(){return ka(this,function(b){return b})}});
var E=moduleArg,la=!!globalThis.window,ma=!!globalThis.WorkerGlobalScope,na,oa,pa,qa=(null==(na=globalThis.process)?void 0:null==(oa=na.versions)?void 0:oa.node)&&"renderer"!=(null==(pa=globalThis.process)?void 0:pa.type);"undefined"!=typeof __filename?_scriptName=__filename:ma&&(_scriptName=self.location.href);var F="",ra,G;
if(qa){var fs=require("fs");F=__dirname+"/";G=function(a){a=H(a)?new URL(a):a;return fs.readFileSync(a)};ra=function(a){var b=void 0===b?!0:b;var c;return D(function(d){a=H(a)?new URL(a):a;c=fs.readFileSync(a,b?void 0:"utf8");return d.return(c)})};process.argv.slice(2)}else if(la||ma){try{F=(new URL(".",_scriptName)).href}catch(a){}ma&&(G=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ra=function(a){var b;return D(function(c){if(1==
c.A)return H(a)?c.return(new Promise(function(d,e){var g=new XMLHttpRequest;g.open("GET",a,!0);g.responseType="arraybuffer";g.onload=function(){200==g.status||0==g.status&&g.response?d(g.response):e(g.status)};g.onerror=e;g.send(null)})):w(c,fetch(a,{credentials:"same-origin"}),2);b=c.D;if(b.ok)return c.return(b.arrayBuffer());throw Error(b.status+" : "+b.url);})}}var sa=console.log.bind(console),I=console.error.bind(console),J,ta=!1;function H(a){return a.startsWith("file://")}
var ua,va,wa,K,L,xa=!1;function ya(){var a=M.buffer;wa=new Int8Array(a);new Int16Array(a);K=new Uint8Array(a);new Uint16Array(a);new Int32Array(a);L=new Uint32Array(a);new Float32Array(a);new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function N(a){var b;null==(b=E.onAbort)||b.call(E,a);a="Aborted("+a+")";I(a);ta=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");var c;null==(c=va)||c(a);throw a;}var O;
function za(a){var b;return D(function(c){switch(c.A){case 1:if(J){c.A=2;break}c.G=3;return w(c,ra(a),5);case 5:return b=c.D,c.return(new Uint8Array(b));case 3:y(c);case 2:var d=c.return;if(a==O&&J)var e=new Uint8Array(J);else if(G)e=G(a);else throw"both async and sync fetching of the wasm failed";return d.call(c,e)}})}
function Aa(a,b){var c,d,e;return D(function(g){switch(g.A){case 1:return g.G=2,w(g,za(a),4);case 4:return c=g.D,w(g,WebAssembly.instantiate(c,b),5);case 5:return d=g.D,g.return(d);case 2:e=y(g),I("failed to asynchronously prepare wasm: "+e),N(e),g.A=0}})}
function Ba(a){var b=J,c=O,d,e,g;return D(function(f){switch(f.A){case 1:if(b||H(c)||qa){f.A=2;break}f.G=3;d=fetch(c,{credentials:"same-origin"});return w(f,WebAssembly.instantiateStreaming(d,a),5);case 5:return e=f.D,f.return(e);case 3:g=y(f),I("wasm streaming compile failed: "+g),I("falling back to ArrayBuffer instantiation");case 2:return f.return(Aa(c,a))}})}function Ca(a){for(;0<a.length;)a.shift()(E)}var Da=[],Ea=[];function Fa(){var a=E.preRun.shift();Ea.push(a)}
function Ga(a){this.B=a-24}var Ha=0,Ia=0,Ja=[null,[],[]],Ka=globalThis.TextDecoder&&new TextDecoder;
function La(a,b){b=void 0===b?0:b;var c=b;for(var d=c+void 0;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ka)return Ka.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function Ma(a){return a?La(K,a):""}
var Na=[];E.print&&(sa=E.print);E.printErr&&(I=E.printErr);E.wasmBinary&&(J=E.wasmBinary);if(E.preInit)for("function"==typeof E.preInit&&(E.preInit=[E.preInit]);0<E.preInit.length;)E.preInit.shift()();
var Oa,Pa,Qa,Ra,Sa,Ta,Ua,Va,Wa,Xa,Ya,Za,$a,ab,M,bb={a:function(a,b,c){var d=new Ga(a);L[d.B+16>>2]=0;L[d.B+4>>2]=b;L[d.B+8>>2]=c;Ha=a;Ia++;throw Ha;},c:function(){return N("")},e:function(a,b){throw"Array index "+a+" out of bounds: [0,"+b+")";},d:function(a){var b=K.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-M.buffer.byteLength+65535)/65536|0;try{M.grow(d);ya();var e=1;break a}catch(g){}e=
void 0}if(e)return!0}return!1},b:function(a,b,c,d){for(var e=0,g=0;g<c;g++){var f=L[b>>2],k=L[b+4>>2];b+=8;for(var m=0;m<k;m++){var p=a,q=K[f+m],B=Ja[p];0===q||10===q?((1===p?sa:I)(La(B)),B.length=0):B.push(q)}e+=k}L[d>>2]=e;return 0}},P;
P=await (function(){function a(e){e=P=e.exports;E._webidl_free=e.h;E._webidl_malloc=e.i;Oa=E._emscripten_bind_Language_getLanguageCode_0=e.j;Pa=E._emscripten_bind_Language___destroy___0=e.k;Qa=E._emscripten_bind_VoidPtr___destroy___0=e.l;Ra=E._emscripten_bind_LanguageGuess_getPercent_0=e.m;Sa=E._emscripten_bind_LanguageGuess_getLanguageCode_0=e.n;Ta=E._emscripten_bind_LanguageGuess___destroy___0=e.o;Ua=E._emscripten_bind_LanguageInfo_detectLanguageWithLength_3=e.p;Va=E._emscripten_bind_LanguageInfo_detectLanguageWithLength_6=
e.q;Wa=E._emscripten_bind_LanguageInfo_detectLanguage_2=e.r;Xa=E._emscripten_bind_LanguageInfo_detectLanguage_5=e.s;Ya=E._emscripten_bind_LanguageInfo_getIsReliable_0=e.t;Za=E._emscripten_bind_LanguageInfo_getLanguageCode_0=e.u;$a=E._emscripten_bind_LanguageInfo_get_languages_1=e.v;ab=E._emscripten_bind_LanguageInfo___destroy___0=e.w;M=e.f;ya();return P}var b,c,d;return D(function(e){if(1==e.A){b={a:bb};if(E.instantiateWasm)return e.return(new Promise(function(g){E.instantiateWasm(b,function(f,k){g(a(f,
k))})}));null!=O||(O=E.locateFile?E.locateFile("cld2.wasm",F):F+"cld2.wasm");return w(e,Ba(b),2)}c=e.D;d=a(c.instance);return e.return(d)})}());
(function(){function a(){E.calledRun=!0;if(!ta){xa=!0;Ca(Na);P.g();var b;null==(b=ua)||b(E);var c;null==(c=E.onRuntimeInitialized)||c.call(E);if(E.postRun)for("function"==typeof E.postRun&&(E.postRun=[E.postRun]);E.postRun.length;)b=E.postRun.shift(),Da.push(b);Ca(Da)}}if(E.preRun)for("function"==typeof E.preRun&&(E.preRun=[E.preRun]);E.preRun.length;)Fa();Ca(Ea);E.setStatus?(E.setStatus("Running..."),setTimeout(function(){setTimeout(function(){return E.setStatus("")},1);a()},1)):a()})();
function Q(){}Q.prototype=Object.create(Q.prototype);Q.prototype.constructor=Q;Q.prototype.J=Q;Q.L={};E.WrapperObject=Q;function cb(a){return(a||Q).L}E.getCache=cb;function R(a,b){var c=cb(b),d=c[a];if(d)return d;d=Object.create((b||Q).prototype);d.B=a;return c[a]=d}E.wrapPointer=R;E.castObject=function(a,b){return R(a.B,b)};E.NULL=R(0);E.destroy=function(a){if(!a.__destroy__)throw"Error: Cannot destroy object. (Did you create it yourself?)";a.__destroy__();delete cb(a.J)[a.B]};
E.compare=function(a,b){return a.B===b.B};E.getPointer=function(a){return a.B};E.getClass=function(a){return a.J};
var S={buffer:0,size:0,N:0,R:[],M:0,P:function(){if(S.M){for(var a=0;a<S.R.length;a++)E._webidl_free(S.R[a]);S.R.length=0;E._webidl_free(S.buffer);S.buffer=0;S.size+=S.M;S.M=0}S.buffer||(S.size+=128,S.buffer=E._webidl_malloc(S.size),S.buffer||N());S.N=0},alloc:function(a,b){S.buffer||N();a=a.length*b.BYTES_PER_ELEMENT;a=8*Math.ceil(a/8);S.N+a>=S.size?(0<a||N(),S.M+=a,b=E._webidl_malloc(a),S.R.push(b)):(b=S.buffer+S.N,S.N+=a);return b}};
function T(a){if("string"===typeof a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}b=Array(b+1);d=b.length;c=0;if(0<d){d=c+d-1;for(var e=0;e<a.length;++e){var g=a.codePointAt(e);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>
6&63;b[c++]=128|g&63;e++}}b[c]=0}a=S.alloc(b,wa);for(c=0;c<b.length;c++)wa[a+c]=b[c];return a}return a}function U(){throw"cannot construct a Language, no constructor in IDL";}U.prototype=Object.create(Q.prototype);U.prototype.constructor=U;U.prototype.J=U;U.L={};E.Language=U;U.prototype.getLanguageCode=function(){return Ma(Oa(this.B))};U.prototype.__destroy__=function(){Pa(this.B)};function V(){throw"cannot construct a VoidPtr, no constructor in IDL";}V.prototype=Object.create(Q.prototype);
V.prototype.constructor=V;V.prototype.J=V;V.L={};E.VoidPtr=V;V.prototype.__destroy__=function(){Qa(this.B)};function W(){throw"cannot construct a LanguageGuess, no constructor in IDL";}W.prototype=Object.create(U.prototype);W.prototype.constructor=W;W.prototype.J=W;W.L={};E.LanguageGuess=W;W.prototype.getPercent=function(){return Ra(this.B)};W.prototype.getLanguageCode=function(){return Ma(Sa(this.B))};W.prototype.__destroy__=function(){Ta(this.B)};
function X(){throw"cannot construct a LanguageInfo, no constructor in IDL";}X.prototype=Object.create(U.prototype);X.prototype.constructor=X;X.prototype.J=X;X.L={};E.LanguageInfo=X;
X.prototype.detectLanguageWithLength=function(a,b,c,d,e,g){S.P();a=a&&"object"===typeof a?a.B:T(a);b&&"object"===typeof b&&(b=b.B);c&&"object"===typeof c&&(c=c.B);d=d&&"object"===typeof d?d.B:T(d);e&&"object"===typeof e&&(e=e.B);g=g&&"object"===typeof g?g.B:T(g);return void 0===d?R(Ua(a,b,c),X):void 0===e?R(_emscripten_bind_LanguageInfo_detectLanguageWithLength_4(a,b,c,d),X):void 0===g?R(_emscripten_bind_LanguageInfo_detectLanguageWithLength_5(a,b,c,d,e),X):R(Va(a,b,c,d,e,g),X)};
X.prototype.detectLanguage=function(a,b,c,d,e){S.P();a=a&&"object"===typeof a?a.B:T(a);b&&"object"===typeof b&&(b=b.B);c=c&&"object"===typeof c?c.B:T(c);d&&"object"===typeof d&&(d=d.B);e=e&&"object"===typeof e?e.B:T(e);return void 0===c?R(Wa(a,b),X):void 0===d?R(_emscripten_bind_LanguageInfo_detectLanguage_3(a,b,c),X):void 0===e?R(_emscripten_bind_LanguageInfo_detectLanguage_4(a,b,c,d),X):R(Xa(a,b,c,d,e),X)};X.prototype.getIsReliable=function(){return!!Ya(this.B)};X.prototype.getLanguageCode=function(){return Ma(Za(this.B))};
X.prototype.get_languages=X.prototype.$=function(a){var b=this.B;a&&"object"===typeof a&&(a=a.B);return R($a(b,a),W)};Object.defineProperty(X.prototype,"languages",{get:X.prototype.$});X.prototype.__destroy__=function(){ab(this.B)};S.alloc=S.alloc.bind(S);S.P=S.P.bind(S);
for(var Y={ISO_8859_1:0,ISO_8859_2:1,ISO_8859_3:2,ISO_8859_4:3,ISO_8859_5:4,ISO_8859_6:5,ISO_8859_7:6,ISO_8859_8:7,ISO_8859_9:8,ISO_8859_10:9,JAPANESE_EUC_JP:10,EUC_JP:10,JAPANESE_SHIFT_JIS:11,SHIFT_JIS:11,JAPANESE_JIS:12,JIS:12,CHINESE_BIG5:13,BIG5:13,CHINESE_GB:14,CHINESE_EUC_CN:15,EUC_CN:15,KOREAN_EUC_KR:16,EUC_KR:16,UNICODE_UNUSED:17,CHINESE_EUC_DEC:18,EUC_DEC:18,CHINESE_CNS:19,CNS:19,CHINESE_BIG5_CP950:20,BIG5_CP950:20,JAPANESE_CP932:21,CP932:21,UTF8:22,UNKNOWN_ENCODING:23,ASCII_7BIT:24,RUSSIAN_KOI8_R:25,
KOI8_R:25,RUSSIAN_CP1251:26,CP1251:26,MSFT_CP1252:27,CP1252:27,RUSSIAN_KOI8_RU:28,KOI8_RU:28,MSFT_CP1250:29,CP1250:29,ISO_8859_15:30,MSFT_CP1254:31,CP1254:31,MSFT_CP1257:32,CP1257:32,ISO_8859_11:33,MSFT_CP874:34,CP874:34,MSFT_CP1256:35,CP1256:35,MSFT_CP1255:36,CP1255:36,ISO_8859_8_I:37,HEBREW_VISUAL:38,CZECH_CP852:39,CP852:39,CZECH_CSN_369103:40,CSN_369103:40,MSFT_CP1253:41,CP1253:41,RUSSIAN_CP866:42,CP866:42,ISO_8859_13:43,ISO_2022_KR:44,GBK:45,GB18030:46,BIG5_HKSCS:47,ISO_2022_CN:48,TSCII:49,TAMIL_MONO:50,
TAMIL_BI:51,JAGRAN:52,MACINTOSH_ROMAN:53,UTF7:54,BHASKAR:55,HTCHANAKYA:56,UTF16BE:57,UTF16LE:58,UTF32BE:59,UTF32LE:60,BINARYENC:61,HZ_GB_2312:62,UTF8UTF8:63,TAM_ELANGO:64,TAM_LTTMBARANI:65,TAM_SHREE:66,TAM_TBOOMIS:67,TAM_TMNEWS:68,TAM_WEBTAMIL:69,KDDI_SHIFT_JIS:70,DOCOMO_SHIFT_JIS:71,SOFTBANK_SHIFT_JIS:72,KDDI_ISO_2022_JP:73,ISO_2022_JP:73,SOFTBANK_ISO_2022_JP:74},db=h(Object.keys(Y)),eb=db.next();!eb.done;eb=db.next()){var fb=eb.value;fb.includes("_")&&(Y[fb.replace(/_/g,"")]=Y[fb])}
E.Encodings=Y;xa?moduleRtn=E:moduleRtn=new Promise(function(a,b){ua=a;va=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=loadCLD2;module.exports.default=loadCLD2}else if(typeof define==="function"&&define["amd"])define([],()=>loadCLD2);
